const defaultData = [
    {
        code:  0,
        image : 'images/iphone16.jpg',
        nom: 'Apple iPhone 16 (128 Go) - Outremer',
        note : 4.5,
        description : 'L’iPhone 16 combine performance, design et intelligence pour répondre aux besoins du quotidien. Équipé d’un écran OLED lumineux de 6,3 pouces, il offre une immersion visuelle remarquable, idéale pour le streaming, les jeux et la navigation. Sa puce A18 Bionic assure une rapidité impressionnante dans toutes les tâches, tandis que le double capteur photo 48 MP capture des images nettes et détaillées, même en basse lumière. Grâce au port USB‑C, la recharge est plus rapide et plus pratique, et l’autonomie a été optimisée pour durer toute la journée. L’iPhone 16 tourne sous iOS 18 avec des fonctions avancées d’intelligence artificielle, de sécurité renforcée et de personnalisation, le tout dans un design épuré en aluminium recyclable, disponible en plusieurs coloris modernes.',
        prix : 870,
        stock : 3,
        categorie : "mobile",
        keyWords :  ["iphone", "apple","iPhone 16",
      "Apple iPhone 16",
      "smartphone Apple",
      "USB-C",
      "A18 Bionic",
      "double caméra 48 MP",
      "iOS 18",
      "iPhone avec IA",
      "recharge rapide",
      "écran OLED 6.3 pouces"]

    },{
        code:  1,
        image : 'images/dell1.jpg',
        nom: 'Dell Inspiron 15 3535',
        note : 4,
        description : 'Le Dell Inspiron 15 3535 est un ordinateur portable élégant et performant conçu pour répondre aux besoins du quotidien, que ce soit pour le travail, les études ou les loisirs. Doté d’un écran 15,6 pouces Full HD (1920 x 1080), il offre une excellente qualité d’affichage pour le multimédia et la bureautique. Son puissant processeur AMD Ryzen 5 7520U, associé à la carte graphique AMD Radeon, garantit une navigation fluide, un multitâche efficace et une bonne réactivité. Il est équipé de 8 Go de RAM et d’un SSD de 512 Go, assurant un démarrage rapide et un espace de stockage confortable pour vos fichiers. Livré avec Windows 11 Home préinstallé, ce modèle intègre un clavier AZERTY français ergonomique et une finition noire sobre et professionnelle, idéale pour un usage quotidien à la maison ou au bureau.',
        prix : 1035,
        stock : 2,
        categorie : 'pc',
        keyWords :  [  "Dell Inspiron 15",
  "Inspiron 3535",
  "ordinateur portable Dell",
  "Dell Ryzen 5",
  "AMD Ryzen 7520U",
  "AMD Radeon Graphics",
  "ordinateur 15.6 pouces",
  "écran Full HD",
  "8Go RAM",
  "512Go SSD",
  "Windows 11 Home",
  "clavier AZERTY",
  "PC portable bureautique",
  "ordinateur étudiant",
  "ordinateur professionnel",
  "Dell noir"]

    },{
        code:  2,
        image : 'images/macBook1.jpg',
        nom: 'Apple MacBook Air 13 Pouces M4',
        note : 4.5,
        description : "Le nouveau MacBook Air 13 pouces avec puce Apple M4 redéfinit la performance et l\'efficacité dans un design ultra-fin. Spécialement conçu pour tirer parti d'Apple Intelligence, il offre une expérience fluide, intelligente et réactive au quotidien. Son superbe écran Liquid Retina de 13,6 pouces affiche des couleurs éclatantes et des détails précis, idéal pour le travail créatif, les études ou le divertissement. Grâce à ses 16 Go de mémoire unifiée et son SSD de 256 Go, ce MacBook Air garantit un multitâche sans compromis et un démarrage instantané. Il intègre également Touch ID pour une sécurité renforcée et une connexion rapide. Sa finition élégante Minuit ajoute une touche de raffinement, le tout dans un boîtier léger et silencieux, parfait pour une mobilité optimale.",
        prix : 1250,
        stock : 1,
        categorie : 'pc',
        keyWords :  [   "MacBook Air M4",
  "Apple MacBook 13 pouces",
  "ordinateur portable Apple",
  "MacBook M4 puce",
  "Apple Intelligence",
  "écran Liquid Retina",
  "MacBook Air 2025",
  "16 Go RAM unifiée",
  "256 Go SSD",
  "Touch ID MacBook",
  "Apple Minuit",
  "Mac portable Apple",
  "ordinateur étudiant Apple",
  "MacBook bureautique",
  "MacBook pour montage vidéo"]

    },{
        code:  4,
        image : 'images/appleWatch1.jpg',
        nom: 'Apple Watch Series 10 (42 mm GPS)',
        note : 3.5,
        description : "L’Apple Watch Series 10 (42 mm GPS) allie élégance, performance et engagement environnemental. Dotée d’un boîtier en aluminium noir de jais et d’une boucle sport encre violette, elle offre un style moderne et raffiné adapté à toutes les occasions. Grâce à ses fonctionnalités avancées, cette montre connectée vous accompagne dans votre quotidien : suivi précis de l’activité physique, surveillance de la fréquence cardiaque, application ECG, et bien plus encore. Son autonomie optimisée et son intégration parfaite avec l’écosystème Apple la rendent indispensable, aussi bien pour les sportifs que pour les utilisateurs soucieux de leur bien-être. Conçue avec des matériaux neutres en carbone, elle reflète également un choix responsable en faveur de l’environnement.",
        prix : 850,
        stock : 4,
        categorie : 'watch',
        keyWords :  ["Apple Watch Series 10",
  "montre connectée Apple",
  "Apple Watch 42 mm",
  "GPS Apple Watch",
  "boîtier aluminium noir de jais",
  "boucle sport encre violette",
  "montre fitness Apple",
  "Apple Watch ECG",
  "montre santé Apple",
  "Apple Watch neutre en carbone",
  "montre sport Apple",
  "suivi activité Apple Watch",
  "Apple Watch femme homme",
  "montre Apple pour iPhone",
  "montre intelligente Apple 2025"]

    },{
        code:  5,
        image : 'images/appleWatch2.jpg',
        nom: 'Apple Watch SE (2ᵉ génération) 40 mm GPS',
        note : 5,
        description : "L’Apple Watch SE (2ᵉ génération) 40 mm est une montre connectée polyvalente au design élégant, dotée d’un boîtier en aluminium argenté et d’une boucle sport nuée bleue confortable. Elle offre un suivi précis de votre activité physique, de votre sommeil, et peut détecter les chutes et accidents grâce à ses capteurs intelligents. Idéale pour un usage quotidien, elle intègre la technologie GPS, fonctionne parfaitement avec votre iPhone, et est conçue de manière responsable avec une empreinte carbone neutre. Cette montre est le choix parfait pour celles et ceux qui recherchent performance, style et bien-être au poignet.",
        prix : 990,
        stock : 1,
        categorie : 'watch',
        keyWords :  [ "Apple Watch SE 2",
  "Apple Watch SE 2e génération",
  "Apple Watch 40 mm",
  "montre connectée Apple",
  "GPS Apple Watch SE",
  "boîtier aluminium argent",
  "boucle sport nuée bleue",
  "montre Apple neutre en carbone",
  "suivi activité Apple Watch",
  "détection accidents Apple Watch",
  "Apple Watch SE sommeil",
  "montre intelligente Apple",
  "Apple Watch iPhone",
  "montre sport Apple Watch SE",
  "Apple Watch SE femme homme"]

    },{
        code:  6,
        image : 'images/S25.jpg',
        nom: 'Samsung Galaxy S25+',
        note : 5,
        description : "Le Samsung Galaxy S25+ est un smartphone Android 5G haut de gamme qui allie puissance, intelligence et élégance. Doté de la technologie Galaxy AI, il optimise chaque tâche du quotidien grâce à l’intelligence artificielle embarquée. Avec ses 256 Go de stockage, il offre amplement d’espace pour vos fichiers, photos et vidéos, tandis que son design raffiné en finition gris métallisé séduit par sa modernité. Équipé d’un chargeur secteur rapide 25W inclus, il garantit une recharge efficace et rapide pour rester toujours connecté. Déverrouillé et prêt à l’emploi, le Galaxy S25+ est le compagnon idéal pour une expérience mobile fluide, intelligente et performante.",
        prix : 1022,
        stock : 2,
        categorie : 'mobile',
        keyWords :  [  "Samsung Galaxy S25+",
  "smartphone 5G",
  "Galaxy AI",
  "téléphone Android",
  "stockage 256 Go",
  "chargeur rapide 25W",
  "smartphone déverrouillé",
  "Samsung S25+ gris",
  "Galaxy S25 Plus",
  "mobile Samsung haut de gamme"]

    },{
        code:  7,
        image : 'images/zflip.jpg',
        nom: 'Samsung Galaxy Z Flip7 FE',
        note : 3.5,
        description : "Le Samsung Galaxy Z Flip7 FE est un smartphone Android 5G innovant qui allie élégance, performance et intelligence. Grâce à la technologie Galaxy AI intégrée, il transforme votre quotidien en optimisant vos tâches avec fluidité et intelligence. Son design pliable emblématique en fait un appareil à la fois compact et stylé, parfait pour allier mobilité et modernité. Avec 256 Go de stockage, vous disposez d’un vaste espace pour conserver vos photos, vidéos et applications. Déverrouillé et prêt à l’emploi, il est livré avec un chargeur secteur rapide 25W pour une recharge efficace à tout moment. Version française, en finition blanche, le Galaxy Z Flip7 FE est le compagnon idéal pour une expérience mobile intelligente, rapide et résolument unique.",
        prix : 999,
        stock : 5,
        categorie : 'mobile',
        keyWords :  [   "Samsung", "Galaxy", "Z Flip7", "Z Flip7 FE", "Flip", "Flip7", 
  "Galaxy Z", "smartphone pliable", "téléphone pliable", "smartphone", 
  "5G", "Galaxy AI", "téléphone Android", "Android", 
  "256 Go", "stockage", "blanc", "version française", "chargeur rapide", 
  "25W", "téléphone déverrouillé", "mobile", "design compact", 
  "intelligence artificielle", "Galaxy Z Flip", "Samsung France", "Galaxy FE"]

    },{
        code:  8,
        image : 'images/16promax.jpg',
        nom: 'Apple iPhone 16 Pro Max (256 Go)',
        note : 4.5,
        description : "L’iPhone 16 Pro Max est le summum de l’innovation Apple, réunissant puissance, élégance et intelligence avancée. Équipé de la puce A18 Pro et d’un écran Super Retina XDR, il offre des performances exceptionnelles et une fluidité inégalée. Grâce à l’intelligence artificielle embarquée et aux fonctionnalités iOS les plus avancées, chaque interaction devient plus intuitive et performante. Son module photo professionnel permet des clichés époustouflants de jour comme de nuit, tandis que sa batterie longue durée et sa compatibilité avec la charge rapide assurent une utilisation prolongée au quotidien. Avec son design raffiné et ses finitions premium, l’iPhone 16 Pro Max s’impose comme l’appareil ultime pour les utilisateurs exigeants à la recherche d’excellence technologique.",
        prix : 1299,
        stock : 0,
        categorie : 'mobile',
        keyWords :  [ "Apple", "iPhone", "iPhone 16", "iPhone 16 Pro", "iPhone 16 Pro Max",
  "iOS", "smartphone Apple", "iPhone nouvelle génération", 
  "A18 Pro", "Super Retina XDR", "photographie mobile", 
  "photo professionnelle", "téléphone haut de gamme", "charge rapide", 
  "batterie longue durée", "design premium", "intelligence artificielle", 
  "IA Apple", "iPhone déverrouillé", "mobile Apple", 
  "performance iPhone", "iPhone 2025", "Apple France", 
  "téléphone 5G", "smartphone iOS"]

    },{
        code:  9,
        image : 'images/15plus.jpg',
        nom: 'Apple iPhone 15 Plus (128 Go) - Rose',
        note : 3,
        description : "L’iPhone 15 Plus est un smartphone Apple 5G qui allie performance, élégance et simplicité d’utilisation. Doté d’un grand écran Super Retina XDR de 6,7 pouces, il offre une expérience visuelle immersive idéale pour le divertissement et la productivité. Grâce à la puce A16 Bionic, il garantit puissance, fluidité et efficacité énergétique au quotidien. Son double appareil photo avancé permet de capturer des clichés nets et lumineux, même en basse lumière. Avec ses 128 Go de stockage, il offre suffisamment d’espace pour vos applications, photos et vidéos. Son design en aluminium et verre teinté dans la masse lui confère un style moderne et résistant. Déverrouillé et prêt à l’emploi, l’iPhone 15 Plus est le compagnon idéal pour une expérience Apple complète et fluide",
        prix : 999,
        stock : 2,
        categorie : 'mobile',
        keyWords :  [  "Apple", "iPhone", "iPhone 15", "iPhone 15 Plus", 
  "smartphone Apple", "iOS", "iPhone 128 Go", 
  "A16 Bionic", "Super Retina XDR", "photo iPhone", 
  "caméra double", "iPhone 2024", "téléphone Apple", 
  "5G Apple", "design aluminium", "verre teinté", 
  "batterie longue durée", "iPhone déverrouillé", 
  "Apple France", "smartphone haut de gamme", 
  "performance iPhone", "écran 6.7 pouces", 
  "expérience fluide", "téléphone iOS", 
  "stockage 128 Go"]

    },{
        code:  10,
        image : 'images/asus.jpg',
        nom: 'ASUS Zenbook 14 UM3406HA-QD048W',
        note : 4,
        description : "Le ASUS Zenbook 14 UM3406HA est un PC portable haut de gamme alliant puissance, finesse et élégance. Doté d’un superbe écran OLED 14 pouces WUXGA, il offre des couleurs éclatantes et un confort visuel optimal, idéal pour le travail comme pour le divertissement. Équipé du processeur AMD Ryzen 7 8840HS cadencé jusqu’à 5.1 GHz, de 16 Go de RAM DDR5X ultra-rapide et d’un SSD de 512 Go, il assure des performances fluides et réactives. Sa carte graphique AMD Radeon intégrée garantit une expérience visuelle fluide pour la bureautique avancée, la création de contenu et les loisirs numériques. Compact, léger, avec un clavier AZERTY confortable et Windows 11 Home préinstallé, ce Zenbook allie mobilité et productivité au quotidien. Son design noir raffiné complète parfaitement ses caractéristiques techniques de pointe.",
        prix : 1299,
        stock : 3,
        categorie : 'pc',
        keyWords :  [  "ASUS", "Zenbook", "Zenbook 14", "UM3406HA", 
  "ordinateur portable", "PC portable ASUS", 
  "écran OLED", "OLED 14 pouces", "WUXGA", 
  "Ryzen 7 8840HS", "AMD Ryzen 7", "5.1 GHz", 
  "16 Go RAM", "DDR5X", "512 Go SSD", 
  "stockage SSD", "AMD Radeon Graphics", 
  "graphismes intégrés", "Windows 11 Home", 
  "PC Windows 11", "clavier AZERTY", 
  "ordinateur noir", "PC compact", "laptop ASUS", 
  "ordinateur performant", "ordinateur léger", 
  "bureautique", "création de contenu", 
  "mobilité", "écran haute qualité"]

    },{
        code:  11,
        image : 'images/micro.jpg',
        nom: 'Microsoft Surface Laptop 4 ',
        note : 4.5,
        description : "Le Microsoft Surface Laptop 4 allie élégance, performance et mobilité dans un format compact et raffiné. Doté d’un écran tactile de 13,5 pouces aux bords fins, il offre une expérience visuelle immersive et une navigation fluide. Son processeur Intel Core i5 assure une réactivité optimale, parfaitement adaptée aux tâches du quotidien et à la bureautique. Avec 8 Go de RAM et 512 Go de stockage SSD, il garantit rapidité et espace pour tous vos fichiers. Sa finition en métal couleur sable apporte une touche de sophistication, tandis que son clavier AZERTY français assure un confort de frappe idéal. Livré avec Windows 11, ce PC portable est conçu pour offrir une productivité fluide dans un design fin et léger, parfait pour les professionnels nomades comme pour un usage personnel exigeant.",
        prix : 1573,
        stock : 3,
        categorie : 'pc',
        keyWords :  [  "Microsoft", "Surface Laptop 4", "Surface", "ordinateur portable",
  "PC portable", "Windows 11", "écran tactile", "13.5 pouces", 
  "Intel Core i5", "Core i5", "processeur Intel", 
  "8 Go RAM", "512 Go SSD", "SSD", "stockage rapide",
  "clavier AZERTY", "clavier français", "ordinateur sable", 
  "finition métal", "ultrabook", "design élégant", 
  "PC léger", "mobilité", "bureautique", "étudiant", 
  "travail", "multimédia", "ordinateur Windows", 
  "Surface i5", "Surface 13 pouces"]

    }
];